config/routes.rb
Rails.application.routes.draw do
  get '/top/index' => 'top#index'
  get '/home/index' => 'home#index'
  post '/command/update' => 'command#update'

  # 徴兵
  get '/conscription/form' => 'conscription#form'
  post '/conscription/update' => 'conscription#update'

  # 戦争
  get '/war/form' => 'war#form'
  post '/war/update' => 'war#update'

  # デバッグ
  post '/debug/execute_command' => 'debug#execute_command'
  post '/debug/change_user' => 'debug#change_user'
end

app/controllers/war_controller.rb
class WarController < ApplicationController
  include InputCommand

  def form
    @command_nos = params[:command_no]
    @towns = Town.all
    @user = User.find(dummy_user_id)
  end

  def update
    input_commands_and_redirect
  end

  def war_command_params
    params.permit(:mode, :town_id)
  end

  def input_command(command_no)
    command = Command.find_or_initialize_by({command_no: command_no}.merge({user_id: dummy_user_id}))
    command.command_type = Command::WAR
    command.save
    if command.war_command.nil?
      command.create_war_command(war_command_params)
    else
      command.war_command.update_attributes(war_command_params)
    end
  end

end

app/helpers/war_helper.rb
module WarHelper
end

app/views/war/form.html.erb
<table border="0" width="100%" height="100%">
  <tbody>
  <tr><td align="center">
    <table border="0" width="100%">
        <tbody><tr><th bgcolor="414141">
            <font color="ffffff"> - 戦 争 - </font>
        </th></tr>
        <tr><td>
          <%= render 'shared/user' %>
        </td></tr>
        <tr><td>
            <tabel bgcolor="#AA0000"></tabel></td></tr><tr><td bgcolor="#000000">
            <font color="white">他国へ侵略をします。<br>隣接する都市へのみ攻撃が可能です。<br>勝利するとその都市を奪えます。<br>敗北した場合は自国へ戻されます。戦争を仕掛ける場合兵士数の<font color="red">２倍の米</font>が必要です。[<a href="http://zizii.vv.cx/map.cgi" target="_blank">勢力図</a>]</font>
        </td></tr></tbody></table>
  </td></tr>
  <tr><td>

  <form action="<%= war_update_path %>" method="POST" id="command_form">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="mode">
    <input type="hidden" name="town_id">
    <% @command_nos.each do |command_no| %>
      <input type="hidden" name="command_no[]" value="<%= command_no %>">
    <% end %>
  </form>

  <table bgcolor="#884422" width="100%" border="0">
    <tbody>
      <tr>
        <td bgcolor="#F0F0F0" width="40%">
          <br>
          <%= @user.town.name %>から戦争可能な街<br><br>
          <input type="radio" name="mode" value="0"><font color="red">未選択</font><br>
          <input type="radio" name="mode" value="5"><font color="red">流言流布を使用する</font><br>
          攻撃都市の民忠を減少させることができます。対人戦のみ発動。金５００が余計にかかります。<br><br>
          <input type="submit" value="攻め込む" id="js-submit_command">
          <%= button_to "戻る", home_index_url, {method: :get} %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= render 'shared/maps/selectable_map' %>
  <hr size="0">
  <center><font color="998877">CGI配布サイト 三国志NET Ver2.8 <a href="http://www3.to/maccyu2/" target="_top">maccyu</a><br><font color="998877">伝説の三国志NET　管理者：<a href="http://densetu.sakura.ne.jp/manual.html#15" target="_blank">伝説じじい</a> 副管理者：FS 史記更新：さやか<br>
      <a href="./index.cgi" target="_top">HOME</a>
      <a href="http://densetusaba.sblo.jp/" target="_blank">_</a>
  </font></font></center></td></tr>
</tbody>
</table>